### ISSUE TITLE
[Summer 2021] Investigate SQL exception raised by SAPP server 

### ISSUE THREAD

**Issue by r0rshark** [MLH-Fellowship/pyre-check#42]
When performing some action on SAPP UI I noticed we are raising a SQL exception

1. `python3 -m sapp.cli server  --source-directory ../zulip`
2. Visit localhost:5000
3. Select a filter and then clear it
The following error is raised

```
2021-08-02 15:29:34,553 [ERROR] Exception during reset or similar
Traceback (most recent call last):
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 682, in _finalize_fairy
    fairy._reset(pool)
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 887, in _reset
    pool._dialect.do_rollback(self)
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 667, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 123145560453120 and this is thread id 123145565708288.
2021-08-02 15:29:34,568 [ERROR] Exception closing connection <sqlite3.Connection object at 0x105044650>
Traceback (most recent call last):
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 682, in _finalize_fairy
    fairy._reset(pool)
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 887, in _reset
    pool._dialect.do_rollback(self)
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 667, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 123145560453120 and this is thread id 123145565708288.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 244, in _close_connection
    self._dialect.do_close(connection)
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 673, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 123145560453120 and this is thread id 123145565708288.
2021-08-02 15:29:34,569 [ERROR] Exception during reset or similar
Traceback (most recent call last):
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 682, in _finalize_fairy
    fairy._reset(pool)
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 887, in _reset
    pool._dialect.do_rollback(self)
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 667, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 123145560453120 and this is thread id 123145565708288.
2021-08-02 15:29:34,569 [ERROR] Exception closing connection <sqlite3.Connection object at 0x105044e30>
Traceback (most recent call last):
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 682, in _finalize_fairy
    fairy._reset(pool)
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 887, in _reset
    pool._dialect.do_rollback(self)
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 667, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 123145560453120 and this is thread id 123145565708288.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 244, in _close_connection
    self._dialect.do_close(connection)
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 673, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 123145560453120 and this is thread id 123145565708288.
2021-08-02 15:29:34,570 [ERROR] Exception during reset or similar
Traceback (most recent call last):
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 682, in _finalize_fairy
    fairy._reset(pool)
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 887, in _reset
    pool._dialect.do_rollback(self)
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 667, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 123145570963456 and this is thread id 123145565708288.
2021-08-02 15:29:34,570 [ERROR] Exception closing connection <sqlite3.Connection object at 0x1053071f0>
Traceback (most recent call last):
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 682, in _finalize_fairy
    fairy._reset(pool)
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 887, in _reset
    pool._dialect.do_rollback(self)
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 667, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 123145570963456 and this is thread id 123145565708288.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 244, in _close_connection
    self._dialect.do_close(connection)
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 673, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 123145570963456 and this is thread id 123145565708288.
2021-08-02 15:29:34,570 [ERROR] Exception during reset or similar
Traceback (most recent call last):
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 682, in _finalize_fairy
    fairy._reset(pool)
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 887, in _reset
    pool._dialect.do_rollback(self)
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 667, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 123145560453120 and this is thread id 123145565708288.
2021-08-02 15:29:34,570 [ERROR] Exception closing connection <sqlite3.Connection object at 0x105307730>
Traceback (most recent call last):
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 682, in _finalize_fairy
    fairy._reset(pool)
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 887, in _reset
    pool._dialect.do_rollback(self)
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 667, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 123145560453120 and this is thread id 123145565708288.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 244, in _close_connection
    self._dialect.do_close(connection)
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 673, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 123145560453120 and this is thread id 123145565708288.
2021-08-02 15:29:34,571 [ERROR] Exception during reset or similar
Traceback (most recent call last):
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 682, in _finalize_fairy
    fairy._reset(pool)
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 887, in _reset
    pool._dialect.do_rollback(self)
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 667, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 123145576218624 and this is thread id 123145565708288.
2021-08-02 15:29:34,571 [ERROR] Exception closing connection <sqlite3.Connection object at 0x105307490>
Traceback (most recent call last):
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 682, in _finalize_fairy
    fairy._reset(pool)
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 887, in _reset
    pool._dialect.do_rollback(self)
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 667, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 123145576218624 and this is thread id 123145565708288.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 244, in _close_connection
    self._dialect.do_close(connection)
  File "/Users/fons/.venvs/sapp/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 673, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 123145576218624 and this is thread id 123145565708288.
```

**Comment by abishekvashok** [comment]
Happens, as mentioned in the exception, when one sqlite3 db connection is used by multiple threads. As long as we performs mutations atomically, we should be good for this solution here: https://stackoverflow.com/a/48234567

ie,
suppress this warning(s).

How does that sound, or should we recreate the connection each time?

**Comment by r0rshark** [comment]
> https://stackoverflow.com/a/48234567

Got it I am still not sure about which are the two threads. My guess is that one is the thread of the main application where the db is created https://github.com/facebook/sapp/blob/master/sapp/ui/server.py#L65 and the other one is the flask server running. In this case I guess it should not be a problem since all the mutation happen in the flask application

**Comment by abishekvashok** [comment]
Yeah my assumption is the same. Making a PR :)

**Comment by abishekvashok** [comment]
Closed via https://github.com/facebook/sapp/commit/bc72d5158b12b9dd77a4530217d43edb2c79f4be
